### ISSUE TITLE
sql issue with going back and forth between dashboard and explore

### ISSUE THREAD

**Issue by gmihir** [ashwinxkumar01/apps-college#3]
Many different errors, all related to multiple queries on one thread. Current fix is to open new thread for each query, need to test more.

**Comment by keskinmbaha** [comment]
Not sure if this issue is a reference to the problem that if you apply a filter on the explore page then you go back to the dashboard and then come back to the explore page, the colleges that you had filtered are still there with the same filters. I did not use the back page button and instead clicked on the dashboard button and the explore page button.

**Comment by keskinmbaha** [comment]
To add onto what I commented above. If you do use the back page button on safari instead, the wrong button stays highlighted on the side nav bar. For example, if I filtered something than clicked on dashboard then clicked on back page on safari, the dashboard button is still white even though I am on the filters page. Same thing happens if you go the other way.
